DEFAULT_TICKERS = [
    'AAPL', 'ABBV', 'AMZN', 'AXP', 'BK', 'CMCSA', 'COST', 'CSCO', 'DUOL',
    'GOOG', 'GM', 'LOW', 'ORCL', 'PEP', 'SHOP', 'SLB', 'SPG', 'TD',
    'SU.TO', 'RY.TO', 'TD.TO', 'SHOP.TO', 'FTG.TO', 'AIM.TO', 'SAP.TO',
    'AW.TO', 'EXE.TO', 'AUST'
]

BENCHMARKS = ['^GSPC', '^GSPTSE']
PORTFOLIO_VALUE_CAD = 1_000_000
MIN_WEIGHT = 0.02
MAX_WEIGHT = 0.15
MIN_AVG_VOLUME = 5_000
MIN_CORRELATION = 0.20
SMALL_CAP_CAD = 2_000_000_000
LARGE_CAP_CAD = 10_000_000_000
DEFAULT_START = '2024-01-01'
FX_FALLBACK = 0.73